name: CI

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened]
  push:
    branches: [master]
  schedule:
    - cron:  '0 8 * * FRI'  # At 08:00 on Friday.

jobs:
  generate_rpg_list:
    name: Generate RPG List
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: sudo apt install -y curl jq
    - shell: bash
      env:
        API_KEY: ${{ secrets.api_key }}
      run: ./build-rpglist.sh "$API_KEY"

    - name: Set date env
      run: echo "TODAY=$(date '+%Y/%m/%d')" >> $GITHUB_ENV

    - name: Update Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: ${{ env.TODAY }}
        files: |
          output/rpglist.json
          output/BlockRpg.ps1
          output/block-rpg.sh
          output/serverlist_full.json
